### ISSUE TITLE
Add `黑皇帝` alias to Chronostasis

### ISSUE THREAD

**Issue by iyume** [TheSnowfield/BotArcAPI#20]
我周围的朋友好像比起 `时停`，更喜欢使用 `黑皇帝` 这个别名

所以我想请问能否将 `黑皇帝` 加入 chronostasis 的 alias

**Comment by TheSnowfield** [comment]
曾經有一段時間, 大量玩家對 `黑皇帝` 產生過爭議.
原因是此別名實際上是作曲者名稱, 而不是具體曲名.
故我們在統計別名時, 爲了避免再次發生這樣的事件, 去除掉了它.

不過, 您可以在自己的 `arcsong.db` 内加入該別名.

**Comment by iyume** [comment]
嗯，谢谢
